### ISSUE TITLE
Where is the BOSH release?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cf-tcp-router#1]
Is there a BOSH release for cf-tcp-router? Thanks!

**Comment by leochu** [comment]
You can find the BOSH release for the cf-tcp-router in the link below.

https://github.com/cloudfoundry-incubator/cf-routing-release

**Comment by drnic** [comment]
Thanks!

**Comment by shalako** [comment]
We'll add a link to the README
